spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/rest_with_spring_boot?useTimezone=true&serverTimezone=UTC
    username: root
    password: bomjesus19
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    #properties:
      #hibernate:
        #dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true